//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace klib.content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Location {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Location() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("klib.content.Location", typeof(Location).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}0001] - Internal error: {1}.
        /// </summary>
        internal static string L00001_1 {
            get {
                return ResourceManager.GetString("L00001_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}0002] - Parameter invalid: {1}.
        /// </summary>
        internal static string L00002_1 {
            get {
                return ResourceManager.GetString("L00002_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}0003] Error to try connect datbase. {1}.
        /// </summary>
        internal static string L00003_1 {
            get {
                return ResourceManager.GetString("L00003_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}0004] The parameter {1}:{2} can&apos;t be null or empty..
        /// </summary>
        internal static string L00004_2 {
            get {
                return ResourceManager.GetString("L00004_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}0005] The formart URL invalid. {1} - {2}.
        /// </summary>
        internal static string L00005_2 {
            get {
                return ResourceManager.GetString("L00005_2", resourceCulture);
            }
        }
    }
}
